name: Refresh GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *" # alle 6 Stunden
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh Stats
        run: |
          echo "Stats refresh gestartet"
